services:
  api-supertasks:
    image: api-supertasks
    build:
      context: .
      dockerfile: SuperTasks.API/Dockerfile
    ports:
      - "80:8080"
    env_file:
      - .env
    networks:
      - supertasks-network
    depends_on:
      - db-supertasks
    
  db-supertasks:
    image: postgres:latest
    container_name: db-supertasks
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - db-supertask-volume:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - supertasks-network

volumes:
  db-supertask-volume:
    
networks:
  supertasks-network:
    driver: bridge
