name: CD-Dev
on:
  push:
    branch: [develop]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image with version tag
        run: docker build -t "${{ secrets.DOCKER_USERNAME }}"/supertasks:latest -f SuperTasks.API\Dockerfile .

      - name: Push Docker image with version tag
        run: docker push "${{ secrets.DOCKER_USERNAME }}"/supertasks:latest