name: CD-Prod
on:
  release: 
    types: [published]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image with version tag
        run: |
          VERSION_TAG=${{ github.ref_name }}
          docker build -t "${{ secrets.DOCKER_USERNAME }}/supertasks:${VERSION_TAG}" -f Dockerfile .

      - name: Push Docker image with version tag
        run: |
          VERSION_TAG=${{ github.ref_name }}
          docker push "${{ secrets.DOCKER_USERNAME }}/supertasks:${VERSION_TAG}"