name: CI-Prod
on:
  push:
    branches: [master, develop]

  pull_request: 
    branches: [master, develop]

jobs: 
  build-and-test:
    if: github.event_name != 'push' || github.event.head_commit.message != 'Merge pull request'
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: '8.0.x'
      - name: Restore Packages
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Run tests
        run: dotnet test --no-build