name: Develop CI-CD
on:
  push:
    branches:
      - develop

  pull_request: 
    branches:
      - develop

jobs: 
  build-application:
    name: Builds the .NET Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: '8.0.x'
      - name: Restore Packages
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
  
  test-application:
    name: Running the application testes
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests
        run: dotnet test --no-build